# Generated by Django 2.1.1 on 2018-10-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='diskname',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='disksize',
        ),
        migrations.RemoveField(
            model_name='newassetapprovalzone',
            name='diskname',
        ),
        migrations.RemoveField(
            model_name='newassetapprovalzone',
            name='disksize',
        ),
        migrations.RemoveField(
            model_name='server',
            name='磁盘名',
        ),
        migrations.RemoveField(
            model_name='server',
            name='磁盘大小',
        ),
        migrations.AddField(
            model_name='newassetapprovalzone',
            name='disk_capacity',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Disk'),
        ),
        migrations.AddField(
            model_name='newassetapprovalzone',
            name='disk_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Disk'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='disk_capacity',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='磁盘容量GB'),
        ),
    ]
