# Generated by Django 2.1.1 on 2018-10-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20181012_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='disk_capacity',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='disk_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
