# Generated by Django 2.1.1 on 2018-10-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20181012_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newassetapprovalzone',
            name='disk_capacity',
        ),
        migrations.RemoveField(
            model_name='newassetapprovalzone',
            name='disk_name',
        ),
        migrations.AddField(
            model_name='newassetapprovalzone',
            name='diskname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='newassetapprovalzone',
            name='disksize',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
