# Generated by Django 2.1.1 on 2018-10-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20181012_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newassetapprovalzone',
            name='diskname',
        ),
        migrations.RemoveField(
            model_name='newassetapprovalzone',
            name='disksize',
        ),
        migrations.AddField(
            model_name='newassetapprovalzone',
            name='family',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
