# Generated by Django 2.1.1 on 2018-10-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20181012_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='newassetapprovalzone',
            name='diskname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
